services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3
    container_name: keycloak-demo
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --http-port=9090
      - --import-realm
    ports:
      - "9090:9090"
    volumes:
      - ./realms:/opt/keycloak/data/import